#ifndef HOOCH_KEY_NAME_H
#define HOOCH_KEY_NAME_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <string.h>
#define HOOCH_PROTOCOL_KEY_NAME_KEY_COUNT      16U
#define HOOCH_PROTOCOL_KEY_NAME_MAX_LENGTH     32U

typedef enum
{
    HOOCH_PROTOCOL_KEY_NAME_RESULT_OK = 0U,
    HOOCH_PROTOCOL_KEY_NAME_RESULT_ERROR,
    HOOCH_PROTOCOL_KEY_NAME_RESULT_INVALID_PARAM,
} HOOCH_PROTOCOL_KeyNameResult_t;

typedef enum
{
    HOOCH_PROTOCOL_KEY_NAME_KEY_INVALID = 0U,
    HOOCH_PROTOCOL_KEY_NAME_KEY_1 = 1U,
    HOOCH_PROTOCOL_KEY_NAME_KEY_2,
    HOOCH_PROTOCOL_KEY_NAME_KEY_3,
    HOOCH_PROTOCOL_KEY_NAME_KEY_4,
    HOOCH_PROTOCOL_KEY_NAME_KEY_5,
    HOOCH_PROTOCOL_KEY_NAME_KEY_6,
    HOOCH_PROTOCOL_KEY_NAME_KEY_7,
    HOOCH_PROTOCOL_KEY_NAME_KEY_8,
    HOOCH_PROTOCOL_KEY_NAME_KEY_9,
    HOOCH_PROTOCOL_KEY_NAME_KEY_10,
    HOOCH_PROTOCOL_KEY_NAME_KEY_11,
    HOOCH_PROTOCOL_KEY_NAME_KEY_12,
    HOOCH_PROTOCOL_KEY_NAME_KEY_13,
    HOOCH_PROTOCOL_KEY_NAME_KEY_14,
    HOOCH_PROTOCOL_KEY_NAME_KEY_15,
    HOOCH_PROTOCOL_KEY_NAME_KEY_16,
} HOOCH_PROTOCOL_KeyNameKey_t;

typedef enum
{
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_0 = 0U,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_1,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_2,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_3,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_4,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_5,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_6,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_7,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_8,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_9,
    HOOCH_PROTOCOL_KEY_NAME_ICON_INDEX_INVALID = 0xFFU,
} HOOCH_PROTOCOL_KeyNameIconIndex_t;

typedef enum
{
    HOOCH_PROTOCOL_KEY_NAME_PAGE_INVALID = 0U,
    HOOCH_PROTOCOL_KEY_NAME_PAGE_SWITCH = 1U,
    HOOCH_PROTOCOL_KEY_NAME_PAGE_SCENE,
    HOOCH_PROTOCOL_KEY_NAME_PAGE_LIGHT,
    HOOCH_PROTOCOL_KEY_NAME_PAGE_CURTAIN,
    HOOCH_PROTOCOL_KEY_NAME_PAGE_LOCAL_SCENE,
} HOOCH_PROTOCOL_KeyNamePage_t;

typedef enum
{
    HOOCH_PROTOCOL_KEY_NAME_CONTENT_TYPE_NAME = 0U,
    HOOCH_PROTOCOL_KEY_NAME_CONTENT_TYPE_DEFAULT_ICON,
    HOOCH_PROTOCOL_KEY_NAME_CONTENT_TYPE_SELECTED_ICON,
} HOOCH_PROTOCOL_KeyNameContentType_t;

typedef enum
{
    HOOCH_PROTOCOL_KEY_NAME_DELIVERY_INVALID = 0U,
    HOOCH_PROTOCOL_KEY_NAME_DELIVERY_KEY = 1U,
    HOOCH_PROTOCOL_KEY_NAME_DELIVERY_OFFSCREEN_TEXT,
} HOOCH_PROTOCOL_KeyNameDelivery_t;

typedef struct
{
    HOOCH_PROTOCOL_KeyNameKey_t key;
    HOOCH_PROTOCOL_KeyNameIconIndex_t icon_index;
    HOOCH_PROTOCOL_KeyNamePage_t page;
    HOOCH_PROTOCOL_KeyNameDelivery_t delivery;
    HOOCH_PROTOCOL_KeyNameContentType_t content_type;
    char name[HOOCH_PROTOCOL_KEY_NAME_MAX_LENGTH];
    uint8_t sequence;
    uint8_t valid; 
    uint8_t value;
} HOOCH_PROTOCOL_KeyNameFrame_t;



typedef void (*HOOCH_PROTOCOL_KeyNameCallback_t)(
    const HOOCH_PROTOCOL_KeyNameFrame_t *frame);

void HOOCH_KeyName_Init(void);
void HOOCH_PROTOCOL_KeyName_Clear(void);
uint8_t HOOCH_PROTOCOL_KeyName_IsValidKey(HOOCH_PROTOCOL_KeyNameKey_t key);
HOOCH_PROTOCOL_KeyNameResult_t HOOCH_PROTOCOL_KeyName_SetName(
    HOOCH_PROTOCOL_KeyNameKey_t key,
    const char *name);
HOOCH_PROTOCOL_KeyNameResult_t HOOCH_PROTOCOL_KeyName_SetFrame(
    const HOOCH_PROTOCOL_KeyNameFrame_t *frame);
const HOOCH_PROTOCOL_KeyNameFrame_t *HOOCH_PROTOCOL_KeyName_GetFrame(void);
const char *HOOCH_PROTOCOL_KeyName_GetName(void);
void HOOCH_PROTOCOL_KeyName_RegisterCallback(
    HOOCH_PROTOCOL_KeyNameCallback_t callback);
void HOOCH_PROTOCOL_KeyName_UnregisterCallback(void);

#ifdef __cplusplus
}
#endif

#endif /* HOOCH_KEY_NAME_H */
